//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public string account1 { get; set; }
        public string acct_desc { get; set; }
        public bool notchange { get; set; }
        public bool cash_acct { get; set; }
        public string acct_type { get; set; }
        public byte[] timestamp { get; set; }
    }
}
