//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class actrea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public actrea()
        {
            this.attempts = new HashSet<attempt>();
            this.setupprms = new HashSet<setupprm>();
        }
    
        public short actreasid { get; set; }
        public string actreas { get; set; }
        public string status { get; set; }
        public string contatmpt { get; set; }
        public byte[] timestamp { get; set; }
        public bool handheld { get; set; }
        public string actreasF { get; set; }
        public string actreasS { get; set; }
        public Nullable<short> letterid { get; set; }
        public bool SendNote { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<attempt> attempts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<setupprm> setupprms { get; set; }
        public virtual letter letter { get; set; }
    }
}
