//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class actstat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public actstat()
        {
            this.actions = new HashSet<action>();
        }
    
        public string status { get; set; }
        public string statusdesc { get; set; }
        public bool resolved { get; set; }
        public bool defstat { get; set; }
        public bool notchange { get; set; }
        public Nullable<int> backcolor { get; set; }
        public Nullable<int> forecolor { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<short> autocall { get; set; }
        public string statusdescF { get; set; }
        public string statusdescS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<action> actions { get; set; }
    }
}
