//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class adjcode
    {
        public string adjcode1 { get; set; }
        public string adj_desc { get; set; }
        public Nullable<decimal> credordeb { get; set; }
        public bool notchange { get; set; }
        public string credacct { get; set; }
        public string debacct { get; set; }
        public bool available { get; set; }
        public bool anybranch { get; set; }
        public byte[] timestamp { get; set; }
        public bool dontreport { get; set; }
        public Nullable<int> backcolor { get; set; }
        public Nullable<int> forecolor { get; set; }
        public string adj_descF { get; set; }
        public string adj_descS { get; set; }
    }
}
