//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class adjust
    {
        public int adjust_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<System.DateTime> adjdate { get; set; }
        public int cust_no { get; set; }
        public string emp_id { get; set; }
        public string adjcode { get; set; }
        public Nullable<decimal> credordeb { get; set; }
        public string note { get; set; }
        public string prepcode { get; set; }
        public Nullable<int> invoice_no { get; set; }
        public string check_no { get; set; }
        public string taxid { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<short> adjreasid { get; set; }
        public string resemp_id { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
