//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class alarm
    {
        public int alarmid { get; set; }
        public string emp_id { get; set; }
        public Nullable<int> favgroupid { get; set; }
        public string alarmmsg { get; set; }
        public Nullable<System.DateTime> lastdate { get; set; }
        public Nullable<System.DateTime> nextdate { get; set; }
        public string repeat { get; set; }
        public Nullable<short> rep_every { get; set; }
        public Nullable<System.DateTime> endon { get; set; }
        public string repeatby { get; set; }
        public byte[] timestamp { get; set; }
    }
}
