//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class alarmsch
    {
        public int alarmschid { get; set; }
        public int alarmid { get; set; }
        public Nullable<System.DateTime> scheddate { get; set; }
        public bool alarm { get; set; }
        public byte[] timestamp { get; set; }
    }
}
