//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class attachxmldata
    {
        public int attachxmldataid { get; set; }
        public int attachid { get; set; }
        public string xmldata { get; set; }
    
        public virtual attach attach { get; set; }
    }
}
