//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class attacat
    {
        public short attacatid { get; set; }
        public string category { get; set; }
        public byte[] timestamp { get; set; }
        public string categoryF { get; set; }
        public string categoryS { get; set; }
    }
}
