//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaitStationActivity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaitStationActivity()
        {
            this.BaitStationActivityNoSrvReas = new HashSet<BaitStationActivityNoSrvRea>();
            this.BaitStationActivityProdUseds = new HashSet<BaitStationActivityProdUsed>();
            this.BaitStationActivityServConds = new HashSet<BaitStationActivityServCond>();
        }
    
        public int BaitStationActivityID { get; set; }
        public int BaitStationID { get; set; }
        public System.DateTime Date { get; set; }
        public int service_id { get; set; }
        public string Comment { get; set; }
        public bool Removed { get; set; }
        public bool Replaced { get; set; }
        public byte[] timestamp { get; set; }
    
        public virtual BaitStation BaitStation { get; set; }
        public virtual service service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaitStationActivityNoSrvRea> BaitStationActivityNoSrvReas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaitStationActivityProdUsed> BaitStationActivityProdUseds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaitStationActivityServCond> BaitStationActivityServConds { get; set; }
    }
}
