//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaitStationActivityServCond
    {
        public int BaitStationActivityServCondID { get; set; }
        public int BaitStationActivityID { get; set; }
        public int servcondid { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public byte[] timestamp { get; set; }
    
        public virtual BaitStationActivity BaitStationActivity { get; set; }
        public virtual servcond servcond { get; set; }
    }
}
