//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaitStation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaitStation()
        {
            this.BaitStationActivities = new HashSet<BaitStationActivity>();
        }
    
        public int BaitStationID { get; set; }
        public int BaitStationTypeID { get; set; }
        public int cust_no { get; set; }
        public string BarCode { get; set; }
        public bool Active { get; set; }
        public string Name { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<short> loc_id { get; set; }
        public string LocationDescription { get; set; }
        public string Note { get; set; }
        public System.DateTime InstallDate { get; set; }
        public Nullable<System.DateTime> LastActivityDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public byte[] timestamp { get; set; }
    
        public virtual BaitStationType BaitStationType { get; set; }
        public virtual customer customer { get; set; }
        public virtual location location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaitStationActivity> BaitStationActivities { get; set; }
    }
}
