//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class batch
    {
        public int batch_no { get; set; }
        public Nullable<System.DateTime> printdate { get; set; }
        public string emp_id { get; set; }
        public string batchtype { get; set; }
        public Nullable<System.DateTime> undodate { get; set; }
        public string undoemp { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<System.DateTime> scheddate { get; set; }
        public Nullable<decimal> drivedist { get; set; }
        public Nullable<short> lunchtime { get; set; }
        public Nullable<byte> lunchlength { get; set; }
    }
}
