//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallTracking
    {
        public int CallTrackingID { get; set; }
        public Nullable<int> cust_no { get; set; }
        public Nullable<int> mcust_no { get; set; }
        public string emp_id { get; set; }
        public Nullable<System.DateTime> CallTime { get; set; }
        public Nullable<long> TrackingID { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual markcust markcust { get; set; }
    }
}
