//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class carrier
    {
        public int carrrte_id { get; set; }
        public string zip { get; set; }
        public string rectype { get; set; }
        public string carr_rte { get; set; }
        public string predir { get; set; }
        public string streetnm { get; set; }
        public string suffix { get; set; }
        public string postdir { get; set; }
        public string primlow { get; set; }
        public string primhigh { get; set; }
        public string primevnodd { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public byte[] timestamp { get; set; }
    }
}
