//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class collcode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public collcode()
        {
            this.customers = new HashSet<customer>();
        }
    
        public short collect_id { get; set; }
        public string coll_desc { get; set; }
        public bool available { get; set; }
        public bool fin_hold { get; set; }
        public string collcode1 { get; set; }
        public byte[] timestamp { get; set; }
        public string agencystat { get; set; }
        public bool nosend { get; set; }
        public Nullable<byte> tier { get; set; }
        public Nullable<short> expiredays { get; set; }
        public string coll_descF { get; set; }
        public string coll_descS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer> customers { get; set; }
    }
}
