//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public company()
        {
            this.CompBaitStationTypes = new HashSet<CompBaitStationType>();
            this.customers = new HashSet<customer>();
            this.QuickTextCompanies = new HashSet<QuickTextCompany>();
            this.CompanyDownTimes = new HashSet<CompanyDownTime>();
            this.RALogs = new HashSet<RALog>();
            this.SS_failed_email = new HashSet<SS_failed_email>();
            this.SS_jobs_transaction_log = new HashSet<SS_jobs_transaction_log>();
            this.SS_srv_log = new HashSet<SS_srv_log>();
            this.CompPackages = new HashSet<CompPackage>();
        }
    
        public int comp_id { get; set; }
        public bool def_comp { get; set; }
        public string compname { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string address3 { get; set; }
        public string phone1 { get; set; }
        public string phone2 { get; set; }
        public string fax { get; set; }
        public string taxid1 { get; set; }
        public string taxid2 { get; set; }
        public string taxid3 { get; set; }
        public byte[] complogo { get; set; }
        public string branchno { get; set; }
        public Nullable<short> salemsgid { get; set; }
        public string state { get; set; }
        public string areacode { get; set; }
        public Nullable<short> unitcode { get; set; }
        public byte[] letterhead { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public string mapsetting { get; set; }
        public Nullable<short> starttime { get; set; }
        public Nullable<short> endtime { get; set; }
        public Nullable<short> marketid { get; set; }
        public byte[] timestamp { get; set; }
        public string clientno { get; set; }
        public string url { get; set; }
        public string aprclient { get; set; }
        public string branchmgr { get; set; }
        public string merchid { get; set; }
        public string terminalid { get; set; }
        public string license { get; set; }
        public Nullable<int> rgsaccount { get; set; }
        public Nullable<System.Guid> token { get; set; }
        public Nullable<short> lunchstart { get; set; }
        public Nullable<short> lunchend { get; set; }
        public Nullable<byte> lunchlength { get; set; }
        public string replyemail { get; set; }
        public Nullable<int> PaymentGateway { get; set; }
        public string ccUser { get; set; }
        public string ccPassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompBaitStationType> CompBaitStationTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer> customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuickTextCompany> QuickTextCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyDownTime> CompanyDownTimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RALog> RALogs { get; set; }
        public virtual CompanyAging CompanyAging { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SS_failed_email> SS_failed_email { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SS_jobs_transaction_log> SS_jobs_transaction_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SS_srv_log> SS_srv_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompPackage> CompPackages { get; set; }
    }
}
