//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class compserv
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public compserv()
        {
            this.compservmesses = new HashSet<compservmess>();
        }
    
        public int compservid { get; set; }
        public int comp_id { get; set; }
        public string serv_code { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<short> mindays { get; set; }
        public Nullable<short> maxdays { get; set; }
        public string @class { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<compservmess> compservmesses { get; set; }
    }
}
