//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class compservmess
    {
        public int compservmessid { get; set; }
        public int compservid { get; set; }
        public string language { get; set; }
        public string servname { get; set; }
        public string longname { get; set; }
        public string inv_msg { get; set; }
        public string inv_smsg { get; set; }
        public string technote { get; set; }
    
        public virtual compserv compserv { get; set; }
    }
}
