//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyAging
    {
        public int comp_id { get; set; }
        public Nullable<decimal> due0_30 { get; set; }
        public Nullable<decimal> due31_45 { get; set; }
        public Nullable<decimal> due46_60 { get; set; }
        public Nullable<decimal> due61_90 { get; set; }
        public Nullable<decimal> dueOver90 { get; set; }
        public Nullable<int> num0_30 { get; set; }
        public Nullable<int> num31_45 { get; set; }
        public Nullable<int> num46_60 { get; set; }
        public Nullable<int> num61_90 { get; set; }
        public Nullable<int> numOver90 { get; set; }
        public byte[] timestamp { get; set; }
    
        public virtual company company { get; set; }
    }
}
