//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class compprod
    {
        public int compprodid { get; set; }
        public int comp_id { get; set; }
        public int prodid { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<decimal> onhand { get; set; }
        public Nullable<decimal> onhold { get; set; }
        public Nullable<decimal> reordpoint { get; set; }
        public string location { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<decimal> unitcost { get; set; }
        public Nullable<decimal> markup { get; set; }
        public Nullable<decimal> unitprice { get; set; }
    }
}
