//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompPackage
    {
        public int CompPackage_ID { get; set; }
        public int Package_ID { get; set; }
        public int comp_id { get; set; }
        public byte[] timestamp { get; set; }
    
        public virtual company company { get; set; }
        public virtual Package Package { get; set; }
    }
}
