//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class compest
    {
        public short compestid { get; set; }
        public int comp_id { get; set; }
        public short estformid { get; set; }
        public byte[] timestamp { get; set; }
    }
}
