//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class condcode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public condcode()
        {
            this.ProductConditions = new HashSet<ProductCondition>();
            this.ProductCondHistories = new HashSet<ProductCondHistory>();
            this.ProductCondJournals = new HashSet<ProductCondJournal>();
        }
    
        public string condcode1 { get; set; }
        public string cond_desc { get; set; }
        public Nullable<short> letterid { get; set; }
        public bool available { get; set; }
        public Nullable<byte> condcatid { get; set; }
        public string custdo { get; set; }
        public Nullable<short> progdefid { get; set; }
        public bool handheld { get; set; }
        public bool anybranch { get; set; }
        public byte[] timestamp { get; set; }
        public bool sendemail { get; set; }
        public string esttext { get; set; }
        public string disccode { get; set; }
        public string cond_descF { get; set; }
        public string cond_descS { get; set; }
        public Nullable<decimal> sortorder { get; set; }
        public string custdoF { get; set; }
        public string custdoS { get; set; }
        public string esttextF { get; set; }
        public string esttextS { get; set; }
        public bool internaluse { get; set; }
        public byte[] Picture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCondition> ProductConditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCondHistory> ProductCondHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCondJournal> ProductCondJournals { get; set; }
    }
}
