//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public contract()
        {
            this.programs = new HashSet<program>();
        }
    
        public int contractid { get; set; }
        public string status { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> payments { get; set; }
        public Nullable<System.DateTime> expiredate { get; set; }
        public int cust_no { get; set; }
        public string notes { get; set; }
        public Nullable<System.DateTime> coupondt { get; set; }
        public Nullable<int> custltrid { get; set; }
        public Nullable<System.DateTime> approvdate { get; set; }
        public bool autorenew { get; set; }
        public bool billcrdcrd { get; set; }
        public Nullable<int> batch_no { get; set; }
        public bool renewed { get; set; }
        public string ponumber { get; set; }
        public byte[] timestamp { get; set; }
    
        public virtual customer customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<program> programs { get; set; }
    }
}
