//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class contpay
    {
        public int contpayid { get; set; }
        public int contractid { get; set; }
        public Nullable<System.DateTime> duedate { get; set; }
        public Nullable<decimal> amount { get; set; }
        public bool billed { get; set; }
        public Nullable<decimal> taxamt1 { get; set; }
        public Nullable<decimal> taxamt2 { get; set; }
        public Nullable<decimal> taxamt3 { get; set; }
        public Nullable<int> invoice_no { get; set; }
        public Nullable<int> prepayid { get; set; }
        public Nullable<decimal> ppayamt { get; set; }
        public byte[] timestamp { get; set; }
    }
}
