//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class crew
    {
        public int crew_id { get; set; }
        public string crewdesc { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public bool permanent { get; set; }
        public Nullable<int> comp_id { get; set; }
        public bool clockedin { get; set; }
        public byte[] timestamp { get; set; }
    }
}
