//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class crrteprg
    {
        public int crrteprgid { get; set; }
        public string route { get; set; }
        public Nullable<short> progdefid { get; set; }
        public int carrzipid { get; set; }
        public string r_c { get; set; }
        public byte[] timestamp { get; set; }
    }
}
