//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class custinv
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public custinv()
        {
            this.custinvgeographyshapes = new HashSet<custinvgeographyshape>();
        }
    
        public int custinv_id { get; set; }
        public int invtry_id { get; set; }
        public Nullable<int> cust_no { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public string inv_notes { get; set; }
        public Nullable<short> loc_id { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<int> mcust_no { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual markcust markcust { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<custinvgeographyshape> custinvgeographyshapes { get; set; }
    }
}
