//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class disccode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public disccode()
        {
            this.customers = new HashSet<customer>();
            this.programs = new HashSet<program>();
            this.services = new HashSet<service>();
            this.PrgmCdPackages = new HashSet<PrgmCdPackage>();
        }
    
        public string disccode1 { get; set; }
        public string disc_desc { get; set; }
        public bool surcharge { get; set; }
        public Nullable<decimal> dollardisc { get; set; }
        public Nullable<decimal> disc_amt { get; set; }
        public bool permanent { get; set; }
        public bool available { get; set; }
        public bool anybranch { get; set; }
        public byte[] timestamp { get; set; }
        public bool webavail { get; set; }
        public string promocode { get; set; }
        public string resacct { get; set; }
        public string comacct { get; set; }
        public string disc_descF { get; set; }
        public string disc_descS { get; set; }
        public bool handheld { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer> customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<program> programs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<service> services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrgmCdPackage> PrgmCdPackages { get; set; }
    }
}
