//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class dontcall
    {
        public int dontcallid { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> importdate { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<System.DateTime> expiredate { get; set; }
        public string source { get; set; }
    }
}
