//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {
            this.attempts = new HashSet<attempt>();
            this.customers = new HashSet<customer>();
            this.QuickTexts = new HashSet<QuickText>();
        }
    
        public string emp_id { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string position { get; set; }
        public bool group_secu { get; set; }
        public Nullable<short> secucode { get; set; }
        public string security { get; set; }
        public string dept { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<System.DateTime> doh { get; set; }
        public Nullable<System.DateTime> dot { get; set; }
        public string gender { get; set; }
        public string mstatus { get; set; }
        public string spouse { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string phone { get; set; }
        public string spouse_ph { get; set; }
        public Nullable<byte> fed_exempt { get; set; }
        public Nullable<byte> st_exempt { get; set; }
        public string ssno { get; set; }
        public string drlicense { get; set; }
        public string comments { get; set; }
        public Nullable<decimal> regrate { get; set; }
        public Nullable<decimal> otrate { get; set; }
        public string paytype { get; set; }
        public Nullable<decimal> deduct1 { get; set; }
        public Nullable<decimal> deduct2 { get; set; }
        public string dednote1 { get; set; }
        public string dednote2 { get; set; }
        public bool active { get; set; }
        public string applicense { get; set; }
        public string email { get; set; }
        public string pageemail { get; set; }
        public Nullable<int> comp_id { get; set; }
        public Nullable<decimal> ottype { get; set; }
        public Nullable<short> otstart { get; set; }
        public byte[] signature { get; set; }
        public Nullable<decimal> adjlimit { get; set; }
        public string exportsec { get; set; }
        public string initials { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<short> lunch { get; set; }
        public Nullable<short> breaktime { get; set; }
        public string lastpass { get; set; }
        public Nullable<System.DateTime> passdate { get; set; }
        public Nullable<int> vehicleid { get; set; }
        public string rptsrvsecu { get; set; }
        public string winuser { get; set; }
        public string language { get; set; }
        public string smtpuserid { get; set; }
        public string smtppassword { get; set; }
        public byte[] Picture { get; set; }
        public string EmployeeBiography1 { get; set; }
        public string EmployeeBiography2 { get; set; }
        public string EmployeeBiography3 { get; set; }
        public Nullable<System.DateTime> EmployeeBiography1Start { get; set; }
        public Nullable<System.DateTime> EmployeeBiography2Start { get; set; }
        public Nullable<System.DateTime> EmployeeBiography3Start { get; set; }
        public Nullable<System.DateTime> EmployeeBiography1End { get; set; }
        public Nullable<System.DateTime> EmployeeBiography2End { get; set; }
        public Nullable<System.DateTime> EmployeeBiography3End { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<attempt> attempts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer> customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuickText> QuickTexts { get; set; }
    }
}
