//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class errorlog
    {
        public int errorlogid { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public string user { get; set; }
        public Nullable<int> err_num { get; set; }
        public string message { get; set; }
        public Nullable<int> line { get; set; }
        public string method { get; set; }
        public string source { get; set; }
        public string alias { get; set; }
        public string trigger { get; set; }
        public string other1 { get; set; }
        public string other2 { get; set; }
        public string memvars { get; set; }
        public byte[] timestamp { get; set; }
    }
}
