//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class estform
    {
        public short estformid { get; set; }
        public string frxname { get; set; }
        public byte[] estform1 { get; set; }
        public string esttitle { get; set; }
        public bool anybranch { get; set; }
        public byte[] timestamp { get; set; }
    }
}
