//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class estimate
    {
        public int estimateid { get; set; }
        public Nullable<System.DateTime> printdate { get; set; }
        public Nullable<int> batch_no { get; set; }
        public int prog_id { get; set; }
        public Nullable<short> estformid { get; set; }
        public string origestby { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<short> sequence { get; set; }
    
        public virtual program program { get; set; }
    }
}
