//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class favgroup
    {
        public int favgroupid { get; set; }
        public string group_name { get; set; }
        public string emp_id { get; set; }
        public bool defsetting { get; set; }
        public bool anybranch { get; set; }
        public byte[] timestamp { get; set; }
    }
}
