//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class favorite
    {
        public int favoriteid { get; set; }
        public int favgroupid { get; set; }
        public string reporttitl { get; set; }
        public string formname { get; set; }
        public Nullable<decimal> outputtype { get; set; }
        public Nullable<decimal> exporttype { get; set; }
        public string exportfile { get; set; }
        public string rptparam { get; set; }
        public string printer { get; set; }
        public Nullable<decimal> copies { get; set; }
        public Nullable<short> frompage { get; set; }
        public Nullable<short> topage { get; set; }
        public bool overwrite { get; set; }
        public byte[] timestamp { get; set; }
        public string rptparam2 { get; set; }
        public Nullable<short> sortorder { get; set; }
    }
}
