//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class flag
    {
        public short flag1 { get; set; }
        public string flag_desc { get; set; }
        public bool available { get; set; }
        public byte[] timestamp { get; set; }
        public bool emphasis { get; set; }
        public bool webavail { get; set; }
        public bool showinv { get; set; }
        public bool showest { get; set; }
        public Nullable<decimal> sortorder { get; set; }
        public Nullable<short> symbol { get; set; }
        public Nullable<int> forecolor { get; set; }
        public Nullable<int> backcolor { get; set; }
        public Nullable<System.DateTime> expdate { get; set; }
        public string notes { get; set; }
        public string flag_descF { get; set; }
        public string flag_descS { get; set; }
    }
}
