//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class franchisefee
    {
        public int fee_id { get; set; }
        public int comp_id { get; set; }
        public Nullable<decimal> royalty { get; set; }
        public Nullable<decimal> outofarea { get; set; }
        public Nullable<decimal> advertize { get; set; }
        public Nullable<bool> chargeoutofarea { get; set; }
        public byte[] timestamp { get; set; }
    }
}
