//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeographyShapeHistory
    {
        public int GeographyShapeHistoryID { get; set; }
        public int GeographyShapeID { get; set; }
        public byte[] Geography { get; set; }
        public string Description { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime HistoryDate { get; set; }
    
        public virtual GeographyShape GeographyShape { get; set; }
    }
}
