//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class histhist
    {
        public int histhistid { get; set; }
        public int hist_id { get; set; }
        public Nullable<int> hist_id2 { get; set; }
        public Nullable<int> service_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public byte[] timestamp { get; set; }
    
        public virtual service service { get; set; }
    }
}
