//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class history
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public history()
        {
            this.HistorySignatures = new HashSet<HistorySignature>();
        }
    
        public int hist_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<System.DateTime> histdate { get; set; }
        public string transcode { get; set; }
        public int cust_no { get; set; }
        public string paytype { get; set; }
        public string emp_id { get; set; }
        public string adjcode { get; set; }
        public string note { get; set; }
        public string check_no { get; set; }
        public string prepcode { get; set; }
        public int comp_id { get; set; }
        public Nullable<int> invoice_no { get; set; }
        public Nullable<System.DateTime> posted { get; set; }
        public string taxid1 { get; set; }
        public string taxid2 { get; set; }
        public string taxid3 { get; set; }
        public Nullable<decimal> taxrate1 { get; set; }
        public Nullable<decimal> taxrate2 { get; set; }
        public Nullable<decimal> taxrate3 { get; set; }
        public Nullable<decimal> tax1 { get; set; }
        public Nullable<decimal> tax2 { get; set; }
        public Nullable<decimal> tax3 { get; set; }
        public Nullable<decimal> ppayamt { get; set; }
        public Nullable<System.DateTime> gldate { get; set; }
        public byte[] timestamp { get; set; }
        public bool reversed { get; set; }
        public Nullable<System.DateTime> paid { get; set; }
        public Nullable<short> adjreasid { get; set; }
        public string resemp_id { get; set; }
        public Nullable<byte> nps { get; set; }
        public string enteredby { get; set; }
    
        public virtual customer customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorySignature> HistorySignatures { get; set; }
    }
}
