//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class imptemp
    {
        public int imptempid { get; set; }
        public string impparams { get; set; }
        public string imptype { get; set; }
        public string seclevel { get; set; }
        public byte[] timestamp { get; set; }
    }
}
