//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public invoice()
        {
            this.services = new HashSet<service>();
        }
    
        public int invoice_no { get; set; }
        public Nullable<System.DateTime> printdate { get; set; }
        public Nullable<decimal> balance { get; set; }
        public Nullable<decimal> prepbal { get; set; }
        public Nullable<decimal> duebal { get; set; }
        public Nullable<int> batch_no { get; set; }
        public string emp_id { get; set; }
        public Nullable<System.DateTime> donedate { get; set; }
        public byte[] timestamp { get; set; }
        public int cust_no { get; set; }
        public Nullable<short> sequence { get; set; }
        public bool tempinv { get; set; }
    
        public virtual customer customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<service> services { get; set; }
    }
}
