//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class langmess
    {
        public string language { get; set; }
        public string paymsg { get; set; }
        public string duemsg2 { get; set; }
        public string duemsg3 { get; set; }
        public string duemsg4 { get; set; }
        public string duemsg5 { get; set; }
        public string duemsg6 { get; set; }
        public string duemsg7 { get; set; }
        public string status0 { get; set; }
        public string status1 { get; set; }
        public string status2 { get; set; }
        public string status3 { get; set; }
        public string status4 { get; set; }
        public string status5 { get; set; }
        public string status6 { get; set; }
        public string status7 { get; set; }
        public string status8 { get; set; }
        public string status9 { get; set; }
        public string contsrvmsg { get; set; }
        public string proposal { get; set; }
        public string remitnone { get; set; }
    }
}
