//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class letter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public letter()
        {
            this.actreas = new HashSet<actrea>();
        }
    
        public short letterid { get; set; }
        public string lettername { get; set; }
        public string lettertext { get; set; }
        public bool available { get; set; }
        public bool confirm { get; set; }
        public bool prepay { get; set; }
        public bool collection { get; set; }
        public bool cancel { get; set; }
        public bool contract { get; set; }
        public bool infoupsell { get; set; }
        public bool useltrhead { get; set; }
        public byte[] ltrobject { get; set; }
        public Nullable<decimal> lettertype { get; set; }
        public byte[] ftop { get; set; }
        public byte[] fbott { get; set; }
        public byte[] btop { get; set; }
        public byte[] bbott { get; set; }
        public string rptparam { get; set; }
        public bool postcard { get; set; }
        public bool anybranch { get; set; }
        public byte[] timestamp { get; set; }
        public bool referral { get; set; }
        public bool pending { get; set; }
        public string rptparam2 { get; set; }
        public System.Guid letter_guid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<actrea> actreas { get; set; }
    }
}
