//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class location
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public location()
        {
            this.BaitStations = new HashSet<BaitStation>();
            this.ProductLocationHistories = new HashSet<ProductLocationHistory>();
            this.ProductLocationJournals = new HashSet<ProductLocationJournal>();
        }
    
        public short loc_id { get; set; }
        public string loc_desc { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<byte> measentry { get; set; }
        public string loc_descf { get; set; }
        public string loc_descs { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaitStation> BaitStations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductLocationHistory> ProductLocationHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductLocationJournal> ProductLocationJournals { get; set; }
    }
}
