//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class mapcode
    {
        public string mapcode1 { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public Nullable<decimal> northlat { get; set; }
        public Nullable<decimal> southlat { get; set; }
        public Nullable<decimal> eastlon { get; set; }
        public Nullable<decimal> westlon { get; set; }
        public int comp_id { get; set; }
        public byte[] timestamp { get; set; }
    }
}
