//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class nosrvrea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nosrvrea()
        {
            this.BaitStationActivityNoSrvReas = new HashSet<BaitStationActivityNoSrvRea>();
        }
    
        public short nosrvid { get; set; }
        public string nosrvdesc { get; set; }
        public byte[] timestamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaitStationActivityNoSrvRea> BaitStationActivityNoSrvReas { get; set; }
    }
}
