//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public payment()
        {
            this.PaymentSignatures = new HashSet<PaymentSignature>();
        }
    
        public int payid { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<System.DateTime> paydate { get; set; }
        public int cust_no { get; set; }
        public string emp_id { get; set; }
        public string paytype { get; set; }
        public string note { get; set; }
        public string check_no { get; set; }
        public string cardacct { get; set; }
        public Nullable<System.DateTime> cardexp { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<byte> nps { get; set; }
        public string enteredby { get; set; }
    
        public virtual customer customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentSignature> PaymentSignatures { get; set; }
    }
}
