//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentSignature
    {
        public int PaymentSignatureID { get; set; }
        public int SignatureID { get; set; }
        public int payid { get; set; }
        public byte[] timestamp { get; set; }
    
        public virtual payment payment { get; set; }
        public virtual Signature Signature { get; set; }
    }
}
