//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class paytype
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public paytype()
        {
            this.customers = new HashSet<customer>();
        }
    
        public string paytype1 { get; set; }
        public string paytypedsc { get; set; }
        public bool credcard { get; set; }
        public string account { get; set; }
        public bool defpaytype { get; set; }
        public bool available { get; set; }
        public byte[] logo { get; set; }
        public byte[] timestamp { get; set; }
        public string lbtype { get; set; }
        public bool ach { get; set; }
        public bool dontreport { get; set; }
        public string paytypedscF { get; set; }
        public string paytypedscS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer> customers { get; set; }
    }
}
