//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class planwk
    {
        public int planid { get; set; }
        public int comp_id { get; set; }
        public Nullable<System.DateTime> weekending { get; set; }
        public Nullable<int> numleads { get; set; }
        public Nullable<int> numsales { get; set; }
        public Nullable<int> numcxls { get; set; }
        public Nullable<int> custcnt { get; set; }
        public Nullable<decimal> totprod { get; set; }
        public string notes { get; set; }
        public short budgetid { get; set; }
        public byte[] timestamp { get; set; }
    }
}
