//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class prepay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prepay()
        {
            this.services = new HashSet<service>();
        }
    
        public int prepayid { get; set; }
        public string prepcode { get; set; }
        public int cust_no { get; set; }
        public Nullable<decimal> prep_amt { get; set; }
        public Nullable<decimal> prep_bal { get; set; }
        public Nullable<decimal> reserved { get; set; }
        public byte[] timestamp { get; set; }
    
        public virtual customer customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<service> services { get; set; }
    }
}
