//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class prepserv
    {
        public int prepservid { get; set; }
        public string prepcode { get; set; }
        public string serv_code { get; set; }
        public byte[] timestamp { get; set; }
    }
}
