//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class pricrang
    {
        public int pricrangid { get; set; }
        public Nullable<decimal> size { get; set; }
        public Nullable<decimal> rate { get; set; }
        public short price_id { get; set; }
        public Nullable<int> estmanhour { get; set; }
        public byte[] timestamp { get; set; }
    }
}
