//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class prodentr
    {
        public int prodentrid { get; set; }
        public int service_id { get; set; }
        public Nullable<System.DateTime> donedate { get; set; }
        public Nullable<decimal> size { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> tax { get; set; }
        public Nullable<decimal> discamt { get; set; }
        public Nullable<decimal> ppayamt { get; set; }
        public Nullable<decimal> totalamt { get; set; }
        public Nullable<decimal> rating { get; set; }
        public Nullable<short> temp { get; set; }
        public Nullable<byte> windspeed { get; set; }
        public string winddir { get; set; }
        public Nullable<short> start { get; set; }
        public Nullable<short> end { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<byte> crewsize { get; set; }
        public Nullable<int> actmanhour { get; set; }
        public string feedback { get; set; }
        public string emp_id { get; set; }
        public Nullable<decimal> ph { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<int> vehicleid { get; set; }
    
        public virtual service service { get; set; }
    }
}
