//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class prodcode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prodcode()
        {
            this.ProductConditions = new HashSet<ProductCondition>();
            this.ProductCodeVehicles = new HashSet<ProductCodeVehicle>();
        }
    
        public int prodid { get; set; }
        public string prodcode1 { get; set; }
        public string prodname { get; set; }
        public string epano { get; set; }
        public Nullable<decimal> onhand { get; set; }
        public Nullable<decimal> onhold { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<decimal> unitcost { get; set; }
        public Nullable<decimal> markup { get; set; }
        public Nullable<decimal> unitprice { get; set; }
        public bool islabor { get; set; }
        public bool po_reqd { get; set; }
        public Nullable<short> prodcatid { get; set; }
        public Nullable<short> unitcode { get; set; }
        public string prop { get; set; }
        public string crew { get; set; }
        public bool forproduc { get; set; }
        public bool forworkord { get; set; }
        public string target { get; set; }
        public bool canupdcost { get; set; }
        public bool ismaster { get; set; }
        public string latinname { get; set; }
        public string sizedesc { get; set; }
        public bool handheld { get; set; }
        public string resacct { get; set; }
        public string comacct { get; set; }
        public bool anybranch { get; set; }
        public byte[] timestamp { get; set; }
        public bool noninv { get; set; }
        public Nullable<decimal> reordpoint { get; set; }
        public string composition { get; set; }
        public string prodnameF { get; set; }
        public string prodnameS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCondition> ProductConditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCodeVehicle> ProductCodeVehicles { get; set; }
    }
}
