//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class progtype
    {
        public string progtype1 { get; set; }
        public string type_desc { get; set; }
        public Nullable<decimal> holdtype { get; set; }
        public byte[] timestamp { get; set; }
        public string type_descf { get; set; }
        public string type_descs { get; set; }
    }
}
