//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class program
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public program()
        {
            this.estimates = new HashSet<estimate>();
            this.services = new HashSet<service>();
            this.ProgramCustomerSignatures = new HashSet<ProgramCustomerSignature>();
        }
    
        public int prog_id { get; set; }
        public int cust_no { get; set; }
        public string status { get; set; }
        public short progdefid { get; set; }
        public Nullable<decimal> size { get; set; }
        public Nullable<short> sourcecd { get; set; }
        public Nullable<System.DateTime> datesold { get; set; }
        public string technote { get; set; }
        public Nullable<System.DateTime> technoteex { get; set; }
        public string custnote { get; set; }
        public Nullable<System.DateTime> custnoteex { get; set; }
        public Nullable<System.DateTime> estreqdate { get; set; }
        public string route { get; set; }
        public string daycode { get; set; }
        public Nullable<short> sequence { get; set; }
        public string soldby1 { get; set; }
        public string soldby2 { get; set; }
        public string disccode { get; set; }
        public Nullable<decimal> stdprice { get; set; }
        public Nullable<decimal> avgprice { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<short> num_serv { get; set; }
        public string billtype { get; set; }
        public Nullable<short> rejcode { get; set; }
        public Nullable<System.DateTime> rej_date { get; set; }
        public Nullable<short> cancode { get; set; }
        public Nullable<System.DateTime> candate { get; set; }
        public string cancelby { get; set; }
        public Nullable<short> holdcode { get; set; }
        public Nullable<System.DateTime> holdbegin { get; set; }
        public Nullable<System.DateTime> holddate { get; set; }
        public Nullable<System.DateTime> lastdate { get; set; }
        public string reqtakenby { get; set; }
        public string estby { get; set; }
        public Nullable<System.DateTime> estprinted { get; set; }
        public Nullable<System.DateTime> estgiven { get; set; }
        public Nullable<System.DateTime> contactdt { get; set; }
        public Nullable<System.DateTime> callbackdt { get; set; }
        public Nullable<int> custltrid { get; set; }
        public bool inconfirm { get; set; }
        public Nullable<int> avetime { get; set; }
        public bool complete { get; set; }
        public string repeat { get; set; }
        public Nullable<short> rep_every { get; set; }
        public Nullable<System.DateTime> endon { get; set; }
        public string repeatby { get; set; }
        public Nullable<byte> callahead { get; set; }
        public Nullable<int> contractid { get; set; }
        public Nullable<short> max { get; set; }
        public Nullable<short> donetd { get; set; }
        public byte[] diagram { get; set; }
        public bool autorenew { get; set; }
        public Nullable<System.DateTime> nextdate { get; set; }
        public string tmproute { get; set; }
        public Nullable<short> tmpseq { get; set; }
        public string tmpday { get; set; }
        public string reqby { get; set; }
        public Nullable<int> refby { get; set; }
        public Nullable<System.DateTime> lastprcchg { get; set; }
        public Nullable<short> season { get; set; }
        public Nullable<decimal> difficulty { get; set; }
        public Nullable<System.DateTime> confdate { get; set; }
        public string ponumber { get; set; }
        public string confby { get; set; }
        public bool renewed { get; set; }
        public Nullable<decimal> wopricing { get; set; }
        public byte[] timestamp { get; set; }
        public bool full { get; set; }
        public string payplanby { get; set; }
        public Nullable<System.DateTime> payplandt { get; set; }
        public bool locksched { get; set; }
        public Nullable<short> mapseq { get; set; }
    
        public virtual callcode callcode { get; set; }
        public virtual cancode cancode1 { get; set; }
        public virtual contract contract { get; set; }
        public virtual custltr custltr { get; set; }
        public virtual customer customer { get; set; }
        public virtual disccode disccode1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estimate> estimates { get; set; }
        public virtual holdcode holdcode1 { get; set; }
        public virtual prgmcd prgmcd { get; set; }
        public virtual rejcode rejcode1 { get; set; }
        public virtual source source { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<service> services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramCustomerSignature> ProgramCustomerSignatures { get; set; }
    }
}
