//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class propinct
    {
        public short invcatid { get; set; }
        public string cat_desc { get; set; }
        public byte[] timestamp { get; set; }
        public string cat_descf { get; set; }
        public string cat_descs { get; set; }
    }
}
