//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class propinv
    {
        public int invtry_id { get; set; }
        public string inv_desc { get; set; }
        public Nullable<short> invcatid { get; set; }
        public Nullable<short> unitcode { get; set; }
        public bool anybranch { get; set; }
        public byte[] timestamp { get; set; }
        public string inv_descf { get; set; }
        public string inv_descs { get; set; }
    }
}
