//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class RALog
    {
        public int RALogID { get; set; }
        public int comp_id { get; set; }
        public string crew { get; set; }
        public Nullable<System.DateTime> donedate { get; set; }
        public Nullable<short> numstops { get; set; }
        public Nullable<decimal> totalcharge { get; set; }
        public byte synchstate { get; set; }
    
        public virtual company company { get; set; }
    }
}
