//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class reptrak
    {
        public int reptrakid { get; set; }
        public string emp_id { get; set; }
        public string loginid { get; set; }
        public string machinenm { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public string whatrep { get; set; }
        public Nullable<int> duration { get; set; }
        public byte[] timestamp { get; set; }
        public string app { get; set; }
    }
}
