//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class route
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public route()
        {
            this.customers = new HashSet<customer>();
            this.CompanyDownTimes = new HashSet<CompanyDownTime>();
        }
    
        public string route1 { get; set; }
        public string route_desc { get; set; }
        public string direction { get; set; }
        public Nullable<int> zone_id { get; set; }
        public bool defwksht { get; set; }
        public bool available { get; set; }
        public bool allprog { get; set; }
        public string mapsetting { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public Nullable<short> starttime { get; set; }
        public Nullable<short> endtime { get; set; }
        public string workweek { get; set; }
        public Nullable<short> mapsymbol { get; set; }
        public int comp_id { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<int> backcolor { get; set; }
        public Nullable<int> forecolor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer> customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyDownTime> CompanyDownTimes { get; set; }
    }
}
