//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class routtrak
    {
        public int routtrakid { get; set; }
        public Nullable<int> prog_id { get; set; }
        public Nullable<int> service_id { get; set; }
        public Nullable<int> invoice_no { get; set; }
        public Nullable<int> estimateid { get; set; }
        public string emp_id { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<System.DateTime> routtrakdt { get; set; }
        public Nullable<int> vehicleid { get; set; }
    
        public virtual service service { get; set; }
        public virtual vehicle vehicle { get; set; }
    }
}
