//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_Employee_Access
    {
        public string emp_id { get; set; }
        public string name { get; set; }
        public string GroupName { get; set; }
        public string SecType { get; set; }
        public bool accessctl { get; set; }
        public bool paypost { get; set; }
        public bool adjpost { get; set; }
        public bool prodpost { get; set; }
        public bool bulkmod { get; set; }
        public bool maintpostper { get; set; }
        public bool glmap { get; set; }
        public bool maintdiscadj { get; set; }
        public bool locnum { get; set; }
        public bool maintpricetbl { get; set; }
        public Nullable<decimal> adjlimit { get; set; }
    }
}
