//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class rptparam
    {
        public int paramkey { get; set; }
        public string emp_id { get; set; }
        public Nullable<int> @int { get; set; }
        public string c1 { get; set; }
        public string c2 { get; set; }
        public string c3 { get; set; }
        public string c5 { get; set; }
        public string c6 { get; set; }
        public Nullable<byte> session { get; set; }
        public string c4 { get; set; }
        public string c8 { get; set; }
        public byte[] timestamp { get; set; }
    }
}
