//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class rtdetail
    {
        public int stopid { get; set; }
        public int routtrakid { get; set; }
        public System.DateTime stoptime { get; set; }
        public decimal latitude { get; set; }
        public decimal longitude { get; set; }
        public int stopcount { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<decimal> mileage { get; set; }
        public Nullable<decimal> speed { get; set; }
        public Nullable<short> actiontype { get; set; }
    }
}
