//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class secStringDetail
    {
        public Nullable<short> securityPos { get; set; }
        public Nullable<short> reportValue { get; set; }
        public Nullable<short> exportsecPos { get; set; }
        public string SecFlagType { get; set; }
        public bool trans_accessControl { get; set; }
        public bool trans_paymentPost { get; set; }
        public bool trans_adjPost { get; set; }
        public bool trans_bulkDataMod { get; set; }
        public bool trans_maintPostingPeriods { get; set; }
        public bool trans_glMapping { get; set; }
        public bool trans_maintDiscAdjParams { get; set; }
        public bool trans_createLocNums { get; set; }
        public bool trans_maintPricingTables { get; set; }
        public bool trans_prodPost { get; set; }
        public string secsetup_Tab { get; set; }
        public string secsetup_Section { get; set; }
        public string secsetup_Item { get; set; }
        public Nullable<short> secsetup_Order { get; set; }
        public string rg_flag { get; set; }
        public string rg_comment { get; set; }
    }
}
