//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class secucode
    {
        public short secucode1 { get; set; }
        public string secu_desc { get; set; }
        public string security { get; set; }
        public Nullable<decimal> adjlimit { get; set; }
        public string exportsec { get; set; }
        public byte[] timestamp { get; set; }
        public string rptsrvsecu { get; set; }
    }
}
