//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SentriconSetup
    {
        public int SentriconSetupID { get; set; }
        public int cust_no { get; set; }
        public bool Active { get; set; }
        public Nullable<byte> InstallationType { get; set; }
        public Nullable<byte> ProductType { get; set; }
        public Nullable<short> ConstructionYear { get; set; }
        public Nullable<byte> Stories { get; set; }
        public Nullable<int> LinearFeet { get; set; }
        public Nullable<short> MonitoringFrequency { get; set; }
        public Nullable<short> BaitedFrequency { get; set; }
        public Nullable<byte> ApplicationType { get; set; }
        public Nullable<byte> TreatmentHistory { get; set; }
        public Nullable<byte> CommercialType { get; set; }
        public Nullable<byte> ResidentialType { get; set; }
        public Nullable<byte> BuildingMaterial { get; set; }
        public Nullable<byte> Condition { get; set; }
        public Nullable<System.DateTime> InstallationDate { get; set; }
        public Nullable<System.DateTime> LastServiceDate { get; set; }
        public Nullable<System.DateTime> NextServiceDate { get; set; }
        public Nullable<System.DateTime> ColonyEliminated { get; set; }
        public Nullable<System.DateTime> AnniversaryDate { get; set; }
        public Nullable<System.DateTime> RetrofitDate { get; set; }
        public Nullable<System.DateTime> AAConversion { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
