//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class servtax
    {
        public int servtaxid { get; set; }
        public Nullable<decimal> taxablepct { get; set; }
        public string serv_code { get; set; }
        public string taxid { get; set; }
        public byte[] timestamp { get; set; }
    }
}
