//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServcdBaitstationtype
    {
        public int ServcdBaitstationtypeID { get; set; }
        public string serv_code { get; set; }
        public int BaitStationTypeID { get; set; }
        public byte[] timestamp { get; set; }
    
        public virtual BaitStationType BaitStationType { get; set; }
        public virtual servcd servcd { get; set; }
    }
}
