//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class servprod
    {
        public int servprodid { get; set; }
        public string serv_code { get; set; }
        public int prodid { get; set; }
        public Nullable<decimal> amount { get; set; }
        public bool anybranch { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<int> comp_id { get; set; }
        public Nullable<short> appmethid { get; set; }
    }
}
