//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public service()
        {
            this.BaitStationActivities = new HashSet<BaitStationActivity>();
            this.donebies = new HashSet<doneby>();
            this.histhists = new HashSet<histhist>();
            this.ppayservs = new HashSet<ppayserv>();
            this.prodentrs = new HashSet<prodentr>();
            this.produseds = new HashSet<prodused>();
            this.routtraks = new HashSet<routtrak>();
            this.servconds = new HashSet<servcond>();
            this.srvnosrvs = new HashSet<srvnosrv>();
            this.tmdetails = new HashSet<tmdetail>();
            this.ServiceCustomerSignatures = new HashSet<ServiceCustomerSignature>();
            this.ServiceEmployeeSignatures = new HashSet<ServiceEmployeeSignature>();
            this.SS_srv_log = new HashSet<SS_srv_log>();
        }
    
        public int service_id { get; set; }
        public int prog_id { get; set; }
        public string serv_code { get; set; }
        public string servstatus { get; set; }
        public Nullable<decimal> size { get; set; }
        public string disccode { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> discamt { get; set; }
        public Nullable<decimal> ppayamt { get; set; }
        public Nullable<decimal> totalamt { get; set; }
        public Nullable<short> round { get; set; }
        public bool dependserv { get; set; }
        public Nullable<int> estmanhour { get; set; }
        public Nullable<System.DateTime> posted { get; set; }
        public Nullable<int> invoice_no { get; set; }
        public Nullable<byte> callahead { get; set; }
        public Nullable<decimal> nextprice { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public string technote { get; set; }
        public Nullable<System.DateTime> technoteex { get; set; }
        public string custnote { get; set; }
        public Nullable<System.DateTime> custnoteex { get; set; }
        public Nullable<int> prepayid { get; set; }
        public Nullable<decimal> manhrrate { get; set; }
        public bool reversed { get; set; }
        public Nullable<decimal> taxblamt1 { get; set; }
        public Nullable<decimal> taxblamt2 { get; set; }
        public Nullable<decimal> taxblamt3 { get; set; }
        public Nullable<decimal> prgdiscamt { get; set; }
        public Nullable<short> startafter { get; set; }
        public Nullable<short> endbefore { get; set; }
        public string assoc { get; set; }
        public Nullable<decimal> prodvalue { get; set; }
        public Nullable<System.DateTime> called { get; set; }
        public bool promised { get; set; }
        public Nullable<decimal> tax1 { get; set; }
        public Nullable<decimal> tax2 { get; set; }
        public Nullable<decimal> tax3 { get; set; }
        public Nullable<decimal> nextsize { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<System.DateTime> datesold { get; set; }
        public string soldby1 { get; set; }
        public string soldby2 { get; set; }
        public Nullable<System.DateTime> asapdate { get; set; }
        public Nullable<short> schedtime { get; set; }
        public string extradesc { get; set; }
        public Nullable<short> mapseq { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaitStationActivity> BaitStationActivities { get; set; }
        public virtual callcode callcode { get; set; }
        public virtual disccode disccode1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doneby> donebies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<histhist> histhists { get; set; }
        public virtual invoice invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ppayserv> ppayservs { get; set; }
        public virtual prepay prepay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prodentr> prodentrs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prodused> produseds { get; set; }
        public virtual program program { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<routtrak> routtraks { get; set; }
        public virtual servcd servcd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<servcond> servconds { get; set; }
        public virtual servhist servhist { get; set; }
        public virtual servstat servstat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<srvnosrv> srvnosrvs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmdetail> tmdetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceCustomerSignature> ServiceCustomerSignatures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceEmployeeSignature> ServiceEmployeeSignatures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SS_srv_log> SS_srv_log { get; set; }
    }
}
