//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class setupprm
    {
        public int paramkey { get; set; }
        public Nullable<System.DateTime> inhistdate { get; set; }
        public bool limitprod { get; set; }
        public bool limitpay { get; set; }
        public Nullable<bool> limitadj { get; set; }
        public Nullable<System.DateTime> prodstart { get; set; }
        public Nullable<System.DateTime> prodend { get; set; }
        public Nullable<System.DateTime> paystart { get; set; }
        public Nullable<System.DateTime> payend { get; set; }
        public Nullable<System.DateTime> adjstart { get; set; }
        public Nullable<System.DateTime> adjend { get; set; }
        public Nullable<short> prepstday { get; set; }
        public Nullable<short> futpstday { get; set; }
        public string country { get; set; }
        public Nullable<short> agedays1 { get; set; }
        public Nullable<short> agedays2 { get; set; }
        public Nullable<short> agedays3 { get; set; }
        public Nullable<short> agedays4 { get; set; }
        public Nullable<short> agedays5 { get; set; }
        public Nullable<short> agedays6 { get; set; }
        public Nullable<decimal> credit_lim { get; set; }
        public Nullable<decimal> rndoffup { get; set; }
        public Nullable<decimal> roundto { get; set; }
        public bool nointprice { get; set; }
        public string invparam { get; set; }
        public string staparam { get; set; }
        public string preparam { get; set; }
        public string prodparam { get; set; }
        public string chngparam { get; set; }
        public Nullable<System.DateTime> agedate { get; set; }
        public Nullable<System.DateTime> intdate { get; set; }
        public Nullable<decimal> statefee { get; set; }
        public Nullable<decimal> comptype { get; set; }
        public Nullable<decimal> lastagecat { get; set; }
        public Nullable<decimal> rolddays { get; set; }
        public Nullable<decimal> colddays { get; set; }
        public Nullable<decimal> roweless { get; set; }
        public Nullable<decimal> coweless { get; set; }
        public bool secprgst0 { get; set; }
        public Nullable<decimal> fiscyrmnth { get; set; }
        public Nullable<decimal> rintstart { get; set; }
        public Nullable<decimal> cintstart { get; set; }
        public Nullable<decimal> rintend { get; set; }
        public Nullable<decimal> cintend { get; set; }
        public Nullable<decimal> upperpropr { get; set; }
        public Nullable<short> season { get; set; }
        public string reqdfields { get; set; }
        public string availstat { get; set; }
        public Nullable<decimal> intorstat { get; set; }
        public Nullable<decimal> invremlim { get; set; }
        public bool chgsc { get; set; }
        public Nullable<decimal> minint { get; set; }
        public Nullable<decimal> intpcnt { get; set; }
        public Nullable<decimal> nointless { get; set; }
        public string mapcdfmt { get; set; }
        public Nullable<decimal> prepcutoff { get; set; }
        public string mappingsw { get; set; }
        public string techparam { get; set; }
        public string estutilfld { get; set; }
        public Nullable<short> progdefid { get; set; }
        public string route { get; set; }
        public string terrcode { get; set; }
        public Nullable<short> sourcecd { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<short> numdays1 { get; set; }
        public Nullable<short> numdays2 { get; set; }
        public Nullable<short> numdays3 { get; set; }
        public Nullable<short> numdays4 { get; set; }
        public Nullable<short> numdays5 { get; set; }
        public string disccode { get; set; }
        public string prepcode { get; set; }
        public Nullable<int> invtry_id { get; set; }
        public string security { get; set; }
        public string exportsec { get; set; }
        public string docsfolder { get; set; }
        public string rptfolder { get; set; }
        public string tmplfolder { get; set; }
        public string helpfolder { get; set; }
        public string pinsfolder { get; set; }
        public string reportdsn { get; set; }
        public string termusers { get; set; }
        public Nullable<System.DateTime> rgchcheck { get; set; }
        public Nullable<short> letterid2 { get; set; }
        public Nullable<short> letterid3 { get; set; }
        public Nullable<short> letterid4 { get; set; }
        public Nullable<short> letterid8 { get; set; }
        public Nullable<short> letterid9 { get; set; }
        public string cawurl { get; set; }
        public Nullable<int> sqldbid { get; set; }
        public Nullable<short> actreasid { get; set; }
        public Nullable<short> maxusers { get; set; }
        public string smtpserver { get; set; }
        public Nullable<int> smtpport { get; set; }
        public Nullable<byte> smtpsecurity { get; set; }
        public Nullable<int> syncsiteid { get; set; }
        public Nullable<System.DateTime> lastRASync { get; set; }
    
        public virtual actrea actrea { get; set; }
    }
}
