//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class sigpoint
    {
        public int sigpointid { get; set; }
        public Nullable<int> sigkey_id { get; set; }
        public short sig_seq { get; set; }
        public string coordx { get; set; }
        public string coordy { get; set; }
        public byte[] timestamp { get; set; }
    }
}
