//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class slscustcarr
    {
        public int cust_no { get; set; }
        public string status { get; set; }
        public string primevnodd { get; set; }
        public string streetno { get; set; }
        public string streetnm { get; set; }
        public string suffix { get; set; }
        public string predir { get; set; }
        public string postdir { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string taxid1 { get; set; }
        public string taxid2 { get; set; }
        public string taxid3 { get; set; }
        public string countyno { get; set; }
        public string carr_rte { get; set; }
    }
}
