//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_jobs_transaction_log
    {
        public int trans_id { get; set; }
        public int header_id { get; set; }
        public int rgs_cust_no { get; set; }
        public string corpcode { get; set; }
        public Nullable<int> cust_no { get; set; }
        public short letterid { get; set; }
        public Nullable<System.DateTime> printdate { get; set; }
        public Nullable<int> mcust_no { get; set; }
        public bool synced { get; set; }
        public string batchtype { get; set; }
        public int prodid { get; set; }
        public string letterurl { get; set; }
        public Nullable<int> comp_id { get; set; }
    
        public virtual company company { get; set; }
        public virtual customer customer { get; set; }
        public virtual markcust markcust { get; set; }
    }
}
