//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_srv_log
    {
        public int srv_id { get; set; }
        public int trans_id { get; set; }
        public Nullable<int> comp_id { get; set; }
        public int service_id { get; set; }
        public Nullable<int> prodid { get; set; }
    
        public virtual company company { get; set; }
        public virtual service service { get; set; }
    }
}
