//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class statemnt
    {
        public int statemntno { get; set; }
        public Nullable<System.DateTime> statemntdt { get; set; }
        public int cust_no { get; set; }
        public Nullable<decimal> balance { get; set; }
        public Nullable<decimal> prepbal { get; set; }
        public Nullable<decimal> duebal { get; set; }
        public Nullable<int> batch_no { get; set; }
        public byte[] timestamp { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
