//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class subassy
    {
        public int subassyid { get; set; }
        public int prodid { get; set; }
        public int subprodid { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public byte[] timestamp { get; set; }
    }
}
