//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class suffix
    {
        public string suffix1 { get; set; }
        public string fullsuffix { get; set; }
        public string alternate1 { get; set; }
        public string alternate2 { get; set; }
        public string alternate3 { get; set; }
        public string alternate4 { get; set; }
        public string alternate5 { get; set; }
        public string alternate6 { get; set; }
        public byte[] timestamp { get; set; }
    }
}
