//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class taxid
    {
        public string taxid1 { get; set; }
        public string taxdesc { get; set; }
        public Nullable<decimal> taxrate { get; set; }
        public bool available { get; set; }
        public string invtaxdesc { get; set; }
        public bool anybranch { get; set; }
        public byte[] timestamp { get; set; }
        public string taxdescf { get; set; }
        public string taxdescs { get; set; }
    }
}
