//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProvidence
    {
        public int ID { get; set; }
        public Nullable<int> Service_Id { get; set; }
        public Nullable<int> Cust_No { get; set; }
        public string Serv_Code { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> StdPrice { get; set; }
    }
}
