//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class terrcode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public terrcode()
        {
            this.customers = new HashSet<customer>();
        }
    
        public string terrcode1 { get; set; }
        public string terr_desc { get; set; }
        public string direction { get; set; }
        public bool available { get; set; }
        public int comp_id { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<int> backcolor { get; set; }
        public Nullable<int> forecolor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer> customers { get; set; }
    }
}
