//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmdetail
    {
        public int tmdetailid { get; set; }
        public int timeheadid { get; set; }
        public Nullable<short> intime { get; set; }
        public Nullable<short> outtime { get; set; }
        public string man_id { get; set; }
        public Nullable<int> service_id { get; set; }
        public Nullable<int> prodid { get; set; }
        public byte[] timestamp { get; set; }
    
        public virtual service service { get; set; }
    }
}
