//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmheader
    {
        public int timeheadid { get; set; }
        public string emp_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<short> reg_min { get; set; }
        public Nullable<short> ot_min { get; set; }
        public Nullable<short> vacation { get; set; }
        public Nullable<short> sick { get; set; }
        public Nullable<short> holiday { get; set; }
        public Nullable<short> other { get; set; }
        public Nullable<short> nonprod { get; set; }
        public bool clockedin { get; set; }
        public string man_id { get; set; }
        public Nullable<decimal> miscamt { get; set; }
        public string comment { get; set; }
        public string nonreason { get; set; }
        public Nullable<short> lunch { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<short> bereavement { get; set; }
        public Nullable<short> personal { get; set; }
    }
}
