//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vehicle()
        {
            this.ProductCodeVehicles = new HashSet<ProductCodeVehicle>();
            this.routtraks = new HashSet<routtrak>();
        }
    
        public int vehicleid { get; set; }
        public string vehdesc { get; set; }
        public string make { get; set; }
        public string model { get; set; }
        public Nullable<short> modelyear { get; set; }
        public string licenseno { get; set; }
        public Nullable<System.DateTime> licenseexp { get; set; }
        public Nullable<int> odometer { get; set; }
        public Nullable<System.DateTime> inservice { get; set; }
        public Nullable<System.DateTime> retired { get; set; }
        public string notes { get; set; }
        public bool available { get; set; }
        public string vin { get; set; }
        public int comp_id { get; set; }
        public byte[] timestamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCodeVehicle> ProductCodeVehicles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<routtrak> routtraks { get; set; }
    }
}
