//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehodom
    {
        public int vehodomid { get; set; }
        public int vehicleid { get; set; }
        public Nullable<int> odometer { get; set; }
        public Nullable<System.DateTime> odomdate { get; set; }
        public string emp_id { get; set; }
        public byte[] timestamp { get; set; }
    }
}
