//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendord
    {
        public int order_id { get; set; }
        public string status { get; set; }
        public int prodid { get; set; }
        public int vendor_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<System.DateTime> bid_print { get; set; }
        public Nullable<System.DateTime> date_ord { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public Nullable<System.DateTime> recv_date { get; set; }
        public string note { get; set; }
        public byte[] timestamp { get; set; }
        public int comp_id { get; set; }
    }
}
