//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReOrient.SA
{
    using System;
    using System.Collections.Generic;
    
    public partial class zipcode
    {
        public string zip { get; set; }
        public string taxid1 { get; set; }
        public string taxid2 { get; set; }
        public string taxid3 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string areacode { get; set; }
        public int comp_id { get; set; }
        public string route { get; set; }
        public string terrcode { get; set; }
        public string alternate1 { get; set; }
        public string alternate2 { get; set; }
        public string alternate3 { get; set; }
        public string alternate4 { get; set; }
        public string alternate5 { get; set; }
        public string alternate6 { get; set; }
        public string alternate7 { get; set; }
        public string alternate8 { get; set; }
        public string alternate9 { get; set; }
        public byte[] timestamp { get; set; }
    }
}
